# Promise
在第 2 章里，我们确定了通过回调表达程序异步和管理并发的两个主要缺陷：缺乏顺序性和可信任性。既然已经对问题有了充分的理解，那么现在是时候把注意力转向可以解决这些问题的模式了。

我们首先想要解决的是控制反转问题，其中，信任很脆弱，也很容易失去。

回忆一下，我们用回调函数来封装程序中的 continuation，然后把回调交给第三方（甚至可能是外部代码），接着期待其能够调用回调，实现正确的功能。

通过这种形式，我们要表达的意思是：“这是将来要做的事情，要在当前的步骤完成之后发生。”

但是，如果我们能够把控制反转再反转回来，会怎样呢？如果我们不把自己程序的continuation 传给第三方，而是希望第三方给我们提供了解其任务何时结束的能力，然后由我们自己的代码来决定下一步做什么，那将会怎样呢？

这种范式就称为 Promise。

随着开发者和规范撰写者绝望地清理他们的代码和设计中由回调地狱引发的疯狂行为，Promise 风暴已经开始席卷 JavaScript 世界。

实际上，绝大多数 JavaScript/DOM 平台新增的异步 API 都是基于 Promise 构建的。所以学习研究 Promise 应该是个好主意，你以为如何呢？！

本章经常会使用“立即”一词，通常用来描述某个 Promise 决议（resolution）动作。但是，基本上在所有情况下，这个“立即”指任务队列行为（参见第1 章）方面的意义，而不是指严格同步的现在。

## 　什么是 Promise
开发人员在学习新技术或新模式时，通常第一步就是“给我看看代码”。对我们来说，先跳进去学习细节是很自然的。

但是，事实证明，只了解 API 会丢失很多抽象的细节。Promise 属于这样一类工具：通过某人使用它的方式，很容易分辨他是真正理解了这门技术，还是仅仅学习和使用 API而已。

所以，在展示 Promise 代码之前，我想先从概念上完整地解释 Promise 到底是什么。希望这能够更好地指导你今后将 Promise 理论集成到自己的异步流中。

### 未来值
每次点芝士汉堡，我都知道最终要么得到一个芝士汉堡，要么得到一个汉堡包售罄的坏消息，那我就得找点别的当午饭了。

>在代码中，事情并非这么简单。这是因为，用类比的方式来说就是，订单号可能永远不会被叫到。在这种情况下，我们就永远处于一种未决议状态。后面会讨论如何处理这种情况。

1. 现在值与将来值
但在具体解释 Promise 的工作方式之前，先来推导通过我们已经理解的方式——回调——如何处理未来值。

当编写代码要得到某个值的时候，比如通过数学计算，不管你有没有意识到，你都已经对这个值做出了一些非常基本的假设，那就是，它已经是一个具体的现在值：
```
var x, y = 2;
console.log( x + y ); // NaN <-- 因为x还没有设定
```

运算 x + y 假定了 x 和 y 都已经设定。用术语简单地解释就是，这里我们假定 x 和 y 的值都是已决议的。

期望运算符 + 本身能够神奇地检测并等待 x 和 y 都决议好（也就是准备好）再进行运算是没有意义的。如果有的语句现在完成，而有的语句将来完成，那就会在程序里引起混乱，对不对？

设想如果可以通过一种方式表达：“把 x 和 y 加起来，但如果它们中的任何一个还没有准备好，就等待两者都准备好。一旦可以就马上执行加运算。”
```
function add(getX,getY,cb) {
    var x, y;
    getX( function(xVal){
        x = xVal;
        // 两个都准备好了？
        if (y != undefined) {
        cb( x + y ); // 发送和
        }
    } );
    getY( function(yVal){
        y = yVal;
        // 两个都准备好了？
        if (x != undefined) {
        cb( x + y ); // 发送和
        }
    } );
}
// fetchX() 和fetchY()是同步或者异步函数
add( fetchX, fetchY, function(sum){
 console.log( sum ); // 是不是很容易？
} ); 
```
先暂停片刻，认真思考一下这段代码的优美度（或缺少优美度，别急着喝彩）。

尽管其中的丑陋不可否认，但这种异步模式体现出了一些非常重要的东西

在这段代码中，我们把 x 和 y 当作未来值，并且表达了一个运算 add(..)。这个运算（从外部看）不在意 x 和 y 现在是否都已经可用。换句话说，它把现在和将来归一化了，因此我们可以确保这个 add(..) 运算的输出是可预测的。

通过使用这个时间上一致的 add(..)——从现在到将来的时间，它的行为都是一致的——大大简化了对这段异步代码的追踪。

当然，这个粗糙的基于回调的方法还有很多不足。要体会追踪未来值的益处而不需要考虑其在时间方面是否可用，这只是很小的第一步。

2. Promise 值
本章后面一定会深入介绍很多 Promise 的细节，因此这里如果读起来有些困惑的话，不必担心。我们先来大致看一下如何通过 Promise 函数表达这个 x + y 的例子：
```
function add(xPromise,yPromise) {
    // Promise.all([ .. ])接受一个promise数组并返回一个新的promise，
    // 这个新promise等待数组中的所有promise完成
    return Promise.all( [xPromise, yPromise] )
    // 这个promise决议之后，我们取得收到的X和Y值并加在一起
    .then( function(values){
    // values是来自于之前决议的promisei的消息数组
    return values[0] + values[1];
    } );
}
// fetchX()和fetchY()返回相应值的promise，可能已经就绪，
// 也可能以后就绪
add( fetchX(), fetchY() )
// 我们得到一个这两个数组的和的promise
// 现在链式调用 then(..)来等待返回promise的决议
.then( function(sum){
 console.log( sum ); // 这更简单！
} ); 
```

这段代码中有两层 Promise。

fetchX() 和 fetchY() 是直接调用的，它们的返回值（promise ！）被传给 add(..)。这些promise 代表的底层值的可用时间可能是现在或将来，但不管怎样，promise 归一保证了行为的一致性。我们可以按照不依赖于时间的方式追踪值 X 和 Y。它们是未来值。

第二层是 add(..)（通过 Promise.all([ .. ])）创建并返回的 promise。我们通过调用then(..) 等待这个 promise。add(..) 运算完成后，未来值 sum 就准备好了，可以打印出来。我们把等待未来值 X 和 Y 的逻辑隐藏在了 add(..) 内部。

就像芝士汉堡订单一样，Promise 的决议结果可能是拒绝而不是完成。拒绝值和完成的 Promise 不一样：完成值总是编程给出的，而拒绝值，通常称为拒绝原因（rejectionreason），可能是程序逻辑直接设置的，也可能是从运行异常隐式得出的值。

通过 Promise，调用 then(..) 实际上可以接受两个函数，第一个用于完成情况（如前所示），第二个用于拒绝情况：
```
add( fetchX(), fetchY() )
.then(
    // 完成处理函数
    function(sum) {
    console.log( sum );
    },
    // 拒绝处理函数
    function(err) {
    console.error( err ); // 烦！
    }
); 
```
如果在获取 X 或 Y 的过程中出错，或者在加法过程中出错，add(..) 返回的就是一个被拒绝的 promise，传给 then(..) 的第二个错误处理回调就会从这个 promise 中得到拒绝值。

从外部看，由于 Promise 封装了依赖于时间的状态——等待底层值的完成或拒绝，所以Promise 本身是与时间无关的。因此，Promise 可以按照可预测的方式组成（组合），而不用关心时序或底层的结果。

另外，一旦 Promise 决议，它就永远保持在这个状态。此时它就成为了不变值（immutablevalue），可以根据需求多次查看。

Promise 决议后就是外部不可变的值，我们可以安全地把这个值传递给第三方，并确信它不会被有意无意地修改。特别是对于多方查看同一个 Promise决议的情况，尤其如此。一方不可能影响另一方对 Promise 决议的观察结果。不可变性听起来似乎一个学术话题，但实际上这是 Promise 设计中最基础和最重要的因素，我们不应该随意忽略这一点

这是关于 Promise 需要理解的最强大也最重要的一个概念。经过大量的工作，你本可以通过丑陋的回调组合专门创建出类似的效果，但这真的不是一个有效的策略，特别是你不得不一次又一次重复操作。

Promise 是一种封装和组合未来值的易于复用的机制。

### 完成事件

如前所述，单独的 Promise 展示了未来值的特性。但是，也可以从另外一个角度看待Promise 的决议：一种在异步任务中作为两个或更多步骤的流程控制机制，时序上的 thisthen-that。

假定要调用一个函数 foo(..) 执行某个任务。我们不知道也不关心它的任何细节。这个函数可能立即完成任务，也可能需要一段时间才能完成。

我们只需要知道 foo(..) 什么时候结束，这样就可以进行下一个任务。换句话说，我们想要通过某种方式在 foo(..) 完成的时候得到通知，以便可以继续下一步。

在典型的 JavaScript 风格中，如果需要侦听某个通知，你可能就会想到事件。因此，可以把对通知的需求重新组织为对 foo(..) 发出的一个完成事件（completion event，或continuation 事件）的侦听。

是叫完成事件还是叫 continuation 事件，取决于你的视角。你是更关注foo(..) 发生了什么，还是更关注 foo(..) 之后发生了什么？两种视角都是合理有用的。事件通知告诉我们 foo(..) 已经完成，也告诉我们现在可以继续进行下一步。确实，传递过去的回调将在事件通知发生时被调用，这个回调本身之前就是我们之前所说的 continuation。完成事件关注 foo(..) 更多一些，这也是目前主要的关注点，所以在后面的内容中，我们将其称为完成事件。

使用回调的话，通知就是任务（foo(..)）调用的回调。而使用 Promise 的话，我们把这个关系反转了过来，侦听来自 foo(..) 的事件，然后在得到通知的时候，根据情况继续。

首先，考虑以下伪代码：

```
foo(x) {
    // 开始做点可能耗时的工作
}
foo( 42 )

on (foo "completion") {
    // 可以进行下一步了！
}
on (foo "error") {
    // 啊，foo(..)中出错了
}
```
我们调用 foo(..)，然后建立了两个事件侦听器，一个用于 "completion"，一个用于"error"——foo(..) 调用的两种可能结果。从本质上讲，foo(..) 并不需要了解调用代码订阅了这些事件，这样就很好地实现了关注点分离。

遗憾的是，这样的代码需要 JavaScript 环境提供某种魔法，而这种环境并不存在（实际上也有点不实际）。以下是在 JavaScript 中更自然的表达方法：

function foo(x) {
 // 开始做点可能耗时的工作
 // 构造一个listener事件通知处理对象来返回
 return listener;
}

var evt = foo( 42 );
evt.on( "completion", function(){
 // 可以进行下一步了！
} );
evt.on( "failure", function(err){
 // 啊，foo(..)中出错了
} ); 

foo(..) 显式创建并返回了一个事件订阅对象，调用代码得到这个对象，并在其上注册了两个事件处理函数。

相对于面向回调的代码，这里的反转是显而易见的，而且这也是有意为之。这里没有把回调传给 foo(..)，而是返回一个名为 evt 的事件注册对象，由它来接受回调。

如果你回想一下第 2 章的话，应该还记得回调本身就表达了一种控制反转。所以对回调模式的反转实际上是对反转的反转，或者称为反控制反转——把控制返还给调用代码，这也是我们最开始想要的效果。

一个很重要的好处是，可以把这个事件侦听对象提供给代码中多个独立的部分；在foo(..) 完成的时候，它们都可以独立地得到通知，以执行下一步：
```
var evt = foo( 42 );
// 让bar(..)侦听foo(..)的完成
bar( evt );
// 并且让baz(..)侦听foo(..)的完成
baz( evt ); 
```

对控制反转的恢复实现了更好的关注点分离，其中 bar(..) 和 baz(..) 不需要牵扯到foo(..) 的调用细节。类似地，foo(..) 不需要知道或关注 bar(..) 和 baz(..) 是否存在，或者是否在等待 foo(..) 的完成通知。

从本质上说，evt 对象就是分离的关注点之间一个中立的第三方协商机制。

### Promise“事件”
你可能已经猜到，事件侦听对象 evt 就是 Promise 的一个模拟。

在基于 Promise 的方法中，前面的代码片段会让 foo(..) 创建并返回一个 Promise 实例，而且这个 Promise 会被传递到 bar(..) 和 baz(..)。

我们侦听的 Promise 决议“事件”严格说来并不算是事件（尽管它们实现目标的行为方式确实很像事件），通常也不叫作 "completion" 或 "error"。事实上，我们通过 then(..) 注册一个 "then" 事件。或者可能更精确地说，then(..) 注册 "fullfillment" 和 / 或 "rejection" 事件，尽管我们并不会在代码中直接使用这些术语。
```
function foo(x) {
 // 可是做一些可能耗时的工作
 // 构造并返回一个promise
 return new Promise( function(resolve,reject){
 // 最终调用resolve(..)或者reject(..)
 // 这是这个promise的决议回调
 } );
}
var p = foo( 42 );
bar( p );
baz( p );   
```

new Promise( function(..){ .. } ) 模式通常称为 revealing constructor（http://domenic.me/2014/02/13/the-revealing-constructor-pattern/）。传入的函数会立即执行（不会像 then(..) 中的回调一样异步延迟），它有两个参数，在本例中我们将其分别称为 resolve 和 reject。这些是 promise 的决议函数。resolve(..) 通常标识完成，而 reject(..) 则标识拒绝。

你可能会猜测 bar(..) 和 baz(..) 的内部实现或许如下：
```
function bar(fooPromise) {
    // 侦听foo(..)完成
    fooPromise.then(
        function(){
            // foo(..)已经完毕，所以执行bar(..)的任务
        },
        function(){
            // 啊，foo(..)中出错了！
        }
    );
}
// 对于baz(..)也是一样
```
Promise 决议并不一定要像前面将 Promise 作为未来值查看时一样会涉及发送消息。它也可以只作为一种流程控制信号，就像前面这段代码中的用法一样.

另外一种实现方式是：
```
function bar() {
    // foo(..)肯定已经完成，所以执行bar(..)的任务
}
function oopsBar() {
    // 啊，foo(..)中出错了，所以bar(..)没有运行
}
// 对于baz()和oopsBaz()也是一样
var p = foo( 42 );
p.then( bar, oopsBar );
p.then( baz, oopsBaz ); 
```

如果以前有过基于 Promise 的编码经验的话，那你可能就会不禁认为前面代码的最后两行可以用链接的方式写作 p.then( .. ).then( .. )，而不是 p.then(..); then(..)。但是，请注意，那样写的话意义就完全不同了！目前二者的区别可能还不是很清晰，但与目前为止我们看到的相比，这确实是一种不同的异步模式——分割与复制。别担心，对于这一点，本章后面还会深入介绍。

这里没有把 promise p 传给 bar(..) 和 baz(..)，而是使用 promise 控制 bar(..) 和 baz(..)何时执行，如果执行的话。最主要的区别在于错误处理部分。

在第一段代码的方法里，不论 foo(..) 成功与否，bar(..) 都会被调用。并且如果收到了foo(..) 失败的通知，它会亲自处理自己的回退逻辑。显然，baz(..) 也是如此。

在第二段代码中，bar(..) 只有在 foo(..) 成功时才会被调用，否则就会调用 oppsBar(..)。baz(..) 也是如此。

这两种方法本身并谈不上对错，只是各自适用于不同的情况。

不管哪种情况，都是从 foo(..) 返回的 promise p 来控制接下来的步骤

另外，两段代码都以使用 promise p 调用 then(..) 两次结束。这个事实说明了前面的观点，就是 Promise（一旦决议）一直保持其决议结果（完成或拒绝）不变，可以按照需要多次查看

一旦 p 决议，不论是现在还是将来，下一个步骤总是相同的。

## 　具有 then 方法的鸭子类型
在 Promise 领域，一个重要的细节是如何确定某个值是不是真正的 Promise。或者更直接地说，它是不是一个行为方式类似于 Promise 的值？

既然 Promise 是通过 new Promise(..) 语法创建的，那你可能就认为可以通过 p instanceof Promise 来检查。但遗憾的是，这并不足以作为检查方法，原因有许多。

其中最主要的是，Promise 值可能是从其他浏览器窗口（iframe 等）接收到的。这个浏览器窗口自己的 Promise 可能和当前窗口 /frame 的不同，因此这样的检查无法识别 Promise实例。

还有，库或框架可能会选择实现自己的 Promise，而不是使用原生 ES6 Promise 实现。实际上，很有可能你是在早期根本没有 Promise 实现的浏览器中使用由库提供的 Promise。

因此，识别 Promise（或者行为类似于 Promise 的东西）就是定义某种称为 thenable 的东西，将其定义为任何具有 then(..) 方法的对象和函数。我们认为，任何这样的值就是Promise 一致的 thenable。

根据一个值的形态（具有哪些属性）对这个值的类型做出一些假定。这种类型检查（typecheck）一般用术语鸭子类型（duck typing）来表示——“如果它看起来像只鸭子，叫起来像只鸭子，那它一定就是只鸭子”（参见本书的“类型和语法”部分）。于是，对 thenable值的鸭子类型检测就大致类似于：
```
if (
    p !== null &&
    (
    typeof p === "object" ||
    typeof p === "function"
    ) &&
    typeof p.then === "function"
) {
    // 假定这是一个thenable!
}else {
    // 不是thenable
} 
```
除了在多个地方实现这个逻辑有点丑陋之外，其实还有一些更深层次的麻烦。

如果你试图使用恰好有 then(..) 函数的一个对象或函数值完成一个 Promise，但并不希望它被当作 Promise 或 thenable，那就有点麻烦了，因为它会自动被识别为 thenable，并被按照特定的规则处理（参见本章后面的内容）。

即使你并没有意识到这个值有 then(..) 函数也是这样。比如：
```
var o = { then: function(){} };
// 让v [[Prototype]]-link到o
var v = Object.create( o );
v.someStuff = "cool";
v.otherStuff = "not so cool";
v.hasOwnProperty( "then" ); // false 
```

v 看起来根本不像 Promise 或 thenable。它只是一个具有一些属性的简单对象。你可能只是想要像对其他对象一样发送这个值。

但你不知道的是，v 还 [[Prototype]] 连接到了另外一个对象 o，而后者恰好具有一个 then(..) 属性。所以thenable 鸭子类型检测会把 v 认作一个 thenable。

甚至不需要是直接有意支持的：
```
Object.prototype.then = function(){};
Array.prototype.then = function(){};
var v1 = { hello: "world" };
var v2 = [ "Hello", "World" ]; 
```
v1 和 v2 都会被认作 thenable。如果有任何其他代码无意或恶意地给 Object.prototype、Array.prototype 或任何其他原生原型添加 then(..)，你无法控制也无法预测。并且，如果指定的是不调用其参数作为回调的函数，那么如果有 Promise 决议到这样的值，就会永远挂住！真是疯狂。

但是别忘了，在 ES6 之前，社区已经有一些著名的非 Promise 库恰好有名为 then(..) 的方法。这些库中有一部分选择了重命名自己的方法以避免冲突（这真糟糕！）。而其他的那些库只是因为无法通过改变摆脱这种冲突，就很不幸地被降级进入了“与基于 Promise 的编码不兼容”的状态。

后面我们就会看到，thenable 鸭子类型检测还是有用的。只是要清楚，如果 thenable 鸭子类型误把不是 Promise 的东西识别为了 Promise，可能就是有害的。

## Promise 信任问题
前面已经给出了两个很强的类比，用于解释 Promise 在不同方面能为我们的异步代码做些什么。但如果止步于此的话，我们就错过了 Promise 模式构建的可能最重要的特性：信任。

未来值和完成事件这两个类比在我们之前探讨的代码模式中很明显。但是，我们还不能一眼就看出 Promise 为什么以及如何用于解决 2.3 节列出的所有控制反转信任问题。稍微深入探究一下的话，我们就不难发现它提供了一些重要的保护，重新建立了第 2 章中已经毁掉的异步编码可信任性。

先回顾一下只用回调编码的信任问题。把一个回调传入工具 foo(..) 时可能出现如下问题：

1. 调用回调过早；
2. 调用回调过晚（或不被调用）；
3. 调用回调次数过少或过多；
4. 未能传递所需的环境和参数；
5. 吞掉可能出现的错误和异常。

Promise 的特性就是专门用来为这些问题提供一个有效的可复用的答案。

### 调用过早
这个问题主要就是担心代码是否会引入类似 Zalgo 这样的副作用（参见第 2 章）。在这类问题中，一个任务有时同步完成，有时异步完成，这可能会导致竞态条件。

根据定义，Promise 就不必担心这种问题，因为即使是立即完成的 Promise（类似于 newPromise(function(resolve){ resolve(42); })）也无法被同步观察到。

也就是说，对一个 Promise 调用 then(..) 的时候，即使这个 Promise 已经决议，提供给then(..) 的回调也总会被异步调用（对此的更多讨论，请参见 1.5 节）。

不再需要插入你自己的 setTimeout(..,0) hack，Promise 会自动防止 Zalgo 出现。

### 调用过晚
和前面一点类似，Promise 创建对象调用 resolve(..) 或 reject(..) 时，这个 Promise 的then(..) 注册的观察回调就会被自动调度。可以确信，这些被调度的回调在下一个异步事件点上一定会被触发（参见 1.5 节）。

同步查看是不可能的，所以一个同步任务链无法以这种方式运行来实现按照预期有效延迟另一个回调的发生。也就是说，一个 Promise 决议后，这个 Promise 上所有的通过then(..) 注册的回调都会在下一个异步时机点上依次被立即调用（再次提醒，请参见 1.5节）。这些回调中的任意一个都无法影响或延误对其他回调的调用。

举例来说：
```
p.then( function(){ 
    p.then( function(){
        console.log( "C" );
    } );
        console.log( "A" );
} );

p.then( function(){
    console.log( "B" );
} );
// A B C 
```
这里，"C" 无法打断或抢占 "B"，这是因为 Promise 的运作方式(决议后，这个 Promise 上所有的通过then(..) 注册的回调都会在下一个异步时机点上依次被立即调用)

### Promise 调度技巧
但是，还有很重要的一点需要指出，有很多调度的细微差别。在这种情况下，两个独立Promise 上链接的回调的相对顺序无法可靠预测。

如果两个 promise p1 和 p2 都已经决议，那么 p1.then(..); p2.then(..) 应该最终会先调用p1 的回调，然后是 p2 的那些。但还有一些微妙的场景可能不是这样的，比如以下代码：
```
var p3 = new Promise( function(resolve,reject){
    resolve( "B" );
} );

var p1 = new Promise( function(resolve,reject){
    resolve( p3 );
} );

p2 = new Promise( function(resolve,reject){
    resolve( "A" );
} );

p1.then( function(v){
    console.log( v );
} ); 
 
p2.then( function(v){
    console.log( v );
} );
// A B <-- 而不是像你可能认为的B A 
```
p1 不是用立即值而是用另一个 promise p3 决议，后者本身决议为值 "B"。规定的行为是把 p3 展开到 p1，但是是异步地展开。所以，在异步任务队列中，p1 的回调排在 p2 的回调之后（参见 1.5 节）。

要避免这样的细微区别带来的噩梦，你永远都不应该依赖于不同 Promise 间回调的顺序和调度。实际上，好的编码实践方案根本不会让多个回调的顺序有丝毫影响，可能的话就要避免。

### 回调未调用
这个问题很常见，Promise 可以通过几种途径解决。

首先，没有任何东西（甚至 JavaScript 错误）能阻止 Promise 向你通知它的决议（如果它决议了的话）。如果你对一个 Promise 注册了一个完成回调和一个拒绝回调，那么 Promise在决议时总是会调用其中的一个。

当然，如果你的回调函数本身包含 JavaScript 错误，那可能就会看不到你期望的结果，但实际上回调还是被调用了。后面我们会介绍如何在回调出错时得到通知，因为就连这些错误也不会被吞掉。

但是，如果 Promise 本身永远不被决议呢？即使这样，Promise 也提供了解决方案，其使用了一种称为竞态的高级抽象机制：
```
// 用于超时一个Promise的工具
function timeoutPromise(delay) {
    return new Promise( function(resolve,reject){
        setTimeout( function(){
            reject( "Timeout!" );
        }, delay );
    } );
}
// 设置foo()超时
Promise.race( [
    foo(), // 试着开始foo()
    timeoutPromise( 3000 ) // 给它3秒钟
] )
.then(
    function(){
        // foo(..)及时完成！
    }, 
    function(err){
        // 或者foo()被拒绝，或者只是没能按时完成
        // 查看err来了解是哪种情况
    }
); 
```
关于这个 Promise 超时模式还有更多细节需要考量，后面我们会深入讨论。

很重要的一点是，我们可以保证一个 foo() 有一个输出信号，防止其永久挂住程序。

### 调用次数过少或过多

根据定义，回调被调用的正确次数应该是 1。“过少”的情况就是调用 0 次，和前面解释过的“未被”调用是同一种情况。

“过多”的情况很容易解释。Promise 的定义方式使得它只能被决议一次。如果出于某种原因，Promise 创建代码试图调用 resolve(..) 或 reject(..) 多次，或者试图两者都调用，那么这个 Promise 将只会接受第一次决议，并默默地忽略任何后续调用。


由于 Promise 只能被决议一次，所以任何通过 then(..) 注册的（每个）回调就只会被调用一次。

当然，如果你把同一个回调注册了不止一次（比如 p.then(f); p.then(f);），那它被调用的次数就会和注册次数相同。响应函数只会被调用一次，但这个保证并不能预防你搬起石头砸自己的脚。




